package com.example.demo.app

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(DemoMutableConfigurationProperties::class, DemoImmutableConfigurationProperties::class)
class DemoConfiguration